pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo Build from Jenkinsfile'
                sh '''
                docker ps
                docker --version
                pwd
                ls -la
                cd jenkins
                ls -la
                '''
            }
        }
    }
}
